#!/usr/bin/env bash

# Prepare libplatform release.
# You need call this script on libplatform root directory.

# The libplatform library is free software; you can redistribute it
# and/or modify it under the terms of the The Unlicense
# as published by the unlicense.org.
# 
# The libplatform library is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the The
# Unlicense for more details.
# 
# You should have received a copy of the The Unlicense
# along with the libplatform library; see the file LICENSE.
# If not, see <https://unlicense.org>.

# Usage: ./prepare-releace [VERSION]
# 

usage()
{
  echo "Usage: $0: [VERSION]"
  exit 1
}

if [ "$1" == "" ]
then
  usage
else
  export VERSION="$1"
fi

# Check git status
if [[ $(git status --porcelain) ]]
then
  # There are uncommitted changes
  git clean -fdxn
  echo "Warning: You need to store uncommitted changes or untracked files, or the release will be unsafe"
  echo "AND YOU UNTRACKED DATA WILL *LOST FOREVER*!!!!!!!!!!"
  exit 1
fi

# Clean repo
git clean -fdx

# Generate files
make -f Makefile.devel

# Add project name to version
export VERSION="libplatform-$VERSION"

# Remove old dist
rm -rf $VERSION

# Copy files
mkdir -p $VERSION

for f in $(ls -d * --color=never); do
  if [ "$f" != "tools" ] && [ "$f" != "$VERSION" ]
  then
    echo "Add file or directory: $f"
    cp -r "$f" $VERSION
  fi
done
