name: 🛠️ Build cppp-platform

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    #--------------------------------------------collect--------------------------------------------
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: 📁 Collect dependencies
      run: |
        sudo apt-get update
        sudo apt-get install p7zip-full zip xz-utils -y
        sudo apt-get install cmake gcc python3 -y
        python -m pip install --upgrade pip
        python -m pip install rubisco

    #--------------------------------------------build--------------------------------------------
    - name: 🛠️ Build distribution
      run: |
        rubisco build
    
    - name: 📦 Make packages
      run: |
        cd dist
        for i in $(ls) ; do sha256sum $i > $i.sha256 ; done
        cd ..
    
    #--------------------------------------------publish--------------------------------------------

    - name: ⬆️ Create release and upload assets
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: ./dist/*
